#%RAML 1.0 Library
uses:

usage:
  result unregistered device from detectID
types:
  detectId:
    description: result unregistered device from detectID
    properties:
        unregisterDeviceResponse:
          properties:
            resultCode:
              type: number
              required: true
              description: code after unregistered device
            resultDescription:
              type: string
              maxLength: 300
              required: true
              description: description code
