#%RAML 1.0 Library
usage: input for clientes
uses:
  headerIn: ../../libraries/type/headerIn.raml
  bodyIn: bodyIn.raml
types:
  eliminarDispositivoDetectId01:
    description: unregistered device from detectId
    properties:
      eliminarDispositivoDetectId01:
        properties:
          headerIn:
            type: headerIn.headerIn
            required: true
          bodyIn:
            type: bodyIn.bodyIn
            required: true
