#%RAML 1.0
title: WSSeguridad0070
baseUri: /Omnicanalidad/IntegrationBus/WSSeguridad0070
version: v1.0
description: Micro services that allows unregistered device in DetectID Cyxtera
uses:
  request: ../resourceTypes/request.raml
  response: ../resourceTypes/response.raml
/WSSeguridad0070:
  post:
    body:
      application/json:
        type: request.eliminarDispositivoDetectId01
        examples:
          # validate client code
          case_1: !include ../examples/case_1/InputFlowSample_1.json
          # validate client code
          case_2: !include ../examples/case_2/InputFlowSample_2.json
    responses:
      200:
        body:
          application/json:
            type: response.eliminarDispositivoDetectId01Response
            examples:
              # Transacction OK. validate client code successful
              case_1: !include ../examples/case_1/OutputFlowSample_1.json
              # Transacction fail: validate client code error
              case_2: !include ../examples/case_2/OutputFlowSample_2.json
