#%RAML 1.0 Library
usage: Output for Clientes
uses:
  headerOut: ../../libraries/type/headerOut.raml
  bodyOut: bodyOut.raml
  error: ../../libraries/type/error.raml
types:
  consultarDispositivosDetectId01Response:
    properties:
      consultarDispositivosDetectId01Response:
        properties:
          headerOut:
            type: headerOut.headerOut
            required: true
          bodyOut:
            type: bodyOut.bodyOut
            required: true
          error:
            type: error.error
            required: true
