#%RAML 1.0 Library
usage:
  log source
types:
  celula:
    description: log source
    properties:
      id:
        type: integer
        required: true
        example:2
      nombre:
        type: string
        required: true
        example:"ONBOARDING"
