#%RAML 1.0 Library
uses:

usage:
  data is necesary for retrieve activation code from detectID
types:
  detectId:
    description: data is necesary for retrieve activation code from detectID
    properties:
      retrieveMobileActivationCode:
        properties:
          processContext:
            properties:
              channelId:
                type: string
                maxLength: 60
                required: true
                description: channel identifier
          sharedKey:
            type: string
            maxLength: 50
            required: true
            description:  shared client code
