#%RAML 1.0 Library
usage: input for clientes
uses:
  headerIn: ../../libraries/type/headerIn.raml
  bodyIn: bodyIn.raml
types:
  consultarMobileActivationCodeDetectId01:
    description: retrieve all devices registered from detectId
    properties:
      consultarMobileActivationCodeDetectId01:
        properties:
          headerIn:
            type: headerIn.headerIn
            required: true
          bodyIn:
            type: bodyIn.bodyIn
            required: true
