#%RAML 1.0 Library
usage: input for clientes
uses:
  headerIn: ../../libraries/type/headerIn.raml
  bodyIn: bodyIn.raml
types:
  consultarValidateDetectId01:
    description: validates client code (softoken)
    properties:
      consultarValidateDetectId01:
        properties:
          headerIn:
            type: headerIn.headerIn
            required: true
          bodyIn:
            type: bodyIn.bodyIn
            required: true
