#%RAML 1.0 Library
usage:
  log source
types:
  criteriosPasivos:
    description: criteria to found info of products about client
    properties:
      periodoConsultaTarjetas:
        type: number
        required: true
        example: 30
        description: days
